const mongoose = require('mongoose');

/**
 * A single bookmark collection with a polymorphic `type` field rather than
 * four separate collections (BookmarkedQuestion, BookmarkedTest, ...) —
 * the access pattern ("show me everything this student saved, optionally
 * filtered by folder") is identical across types, so one schema + one index
 * beats four near-identical ones.
 */
const bookmarkSchema = new mongoose.Schema(
  {
    student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    type: { type: String, enum: ['question', 'topic', 'test', 'formula'], required: true },
    refId: { type: mongoose.Schema.Types.ObjectId, required: true }, // points at Question/Topic/Test depending on `type`
    folder: { type: String, default: 'Default' },
    note: { type: String },
  },
  { timestamps: true }
);
bookmarkSchema.index({ student: 1, type: 1, refId: 1 }, { unique: true });

/**
 * One row per (student, question, stage). Generated by ruleEngine.buildRevisionQueue
 * on Day 1/3/7/15/30 whenever a question is answered incorrectly. A cron/worker
 * (see README) promotes `status` to 'due' when `dueAt` passes.
 */
const revisionQueueSchema = new mongoose.Schema(
  {
    student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    question: { type: mongoose.Schema.Types.ObjectId, ref: 'Question', required: true },
    sourceAttempt: { type: mongoose.Schema.Types.ObjectId, ref: 'TestAttempt' },
    stage: { type: Number, required: true }, // 1..5, maps to the Day 1/3/7/15/30 schedule
    dueAt: { type: Date, required: true, index: true },
    status: { type: String, enum: ['pending', 'due', 'completed', 'wrong_again'], default: 'pending' },
    completedAt: { type: Date },
  },
  { timestamps: true }
);

const auditLogSchema = new mongoose.Schema(
  {
    actor: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    action: { type: String, required: true }, // e.g. "QUESTION_APPROVED", "TEST_PUBLISHED"
    entityType: { type: String, required: true },
    entityId: { type: mongoose.Schema.Types.ObjectId, required: true },
    metadata: { type: mongoose.Schema.Types.Mixed },
    ipAddress: { type: String },
  },
  { timestamps: true }
);
auditLogSchema.index({ entityType: 1, entityId: 1 });

module.exports = {
  Bookmark: mongoose.model('Bookmark', bookmarkSchema),
  RevisionQueue: mongoose.model('RevisionQueue', revisionQueueSchema),
  AuditLog: mongoose.model('AuditLog', auditLogSchema),
};
